### ISSUE TITLE
Create Session detail view

### ISSUE THREAD

**Issue by jrrickerson** [pyatl/podium-django#3]
Create a view that allows a user to view a particular Session.  This detail view should list all talks associated with this session that have a status of "Approved" or "Confirmed."  Each talk in the list should be a link to the Talk Detail view for that Talk.

**Comment by luther9** [comment]
I'm currently working on this one. I've made the appropriate links in the session list view. I still need to implement the session detail view.

**Comment by jrrickerson** [comment]
Sounds good.  Looking forward to the PR!

**Comment by jrrickerson** [comment]
Closed by #29
