### ISSUE TITLE
Incorporate Travis CI with linter

### ISSUE THREAD

**Issue by jbonzo** [pyatl/podium-django#30]
Travis CI is a [continuous integration tool](https://www.thoughtworks.com/continuous-integration) that is used to monitor the status of code 24/7. It can be used to automatically run tests (unit or integration) and can also check other requirements such as style and linting.

In order for this task to be complete it must satisfy these criteria:
- Runs the designated tasks for each branch and PR

- Restricts merging a PR to master if the build is not passing

- Has the task of linting with a tool such as flake8

There will most likely be permissions required for this, mostly on the github side. I believe currently @jrrickerson is the person to ask about that. Permissions might include:

- Github API key for travis

- Protecting master from merges unless builds pass

**Comment by jrrickerson** [comment]
You've been granted admin permission to the repo if you'd like to tackle this one, so I've gone ahead and assigned it to you.  If you'd rather not work on it, let me know and I'll unassign you so someone else can take a look at it.

**Comment by jbonzo** [comment]
I will take this on

**Comment by jbonzo** [comment]
Unfortunately @jrrickerson you are a bottleneck for the travis setup. https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator

**Comment by jrrickerson** [comment]
I've set up the basic Travis CI access, so hopefully that unblocks you.  Let me know if you need anything else.

**Comment by jrrickerson** [comment]
Closed by #36
