### ISSUE TITLE
Should anyone be allowed to edit titles/descriptions/labels for Issues

### ISSUE THREAD

**Issue by jbonzo** [pyatl/podium-django#31]
I recently made an Issue on this repo and can't add labels
@jrrickerson

**Comment by jrrickerson** [comment]
Thanks for the question!

Unfortunately, Github's current permissions model won't allow the ability to add labels to issues unless the user has write access to the repo.  By default, everyone has read access to the repo and can additionally *submit* issues, and can edit / close their own submitted issues.
https://help.github.com/articles/repository-permission-levels-for-an-organization/

While I'm not opposed to adding more maintainers to help organize issues, especially as this project grows, I'm afraid the project might become unmanageable if a very large number of people had write access, especially those just beginning to learn how to use Github.

In addition, most open source projects you'll find in the wild will not allow write access to the repository until they see repeated contributions from an individual, so keeping the default read-only permission is likely a better scenario for educating newcomers to these sorts of projects.

Let me know if that clears it up for you!

**Comment by jbonzo** [comment]
It does. Thanks

**Comment by jrrickerson** [comment]
Closing as answered
