### ISSUE TITLE
Remove generic template carousel from Index view

### ISSUE THREAD

**Issue by jrrickerson** [pyatl/podium-django#32]
The current index view contains a carousel widget which appears to contain generic text from a theme template.  Remove the carousel widget and replace it with simple descriptive text.  The text should include the basic information about PyATL and the use of this project:
- Brief description of what PyATL is
- Link to the PyATL meetup site
- Brief description of the purpose of the Podium tool (for submitting talk proposals)
- Brief byline stating that the project is maintained by PyATL Jam Session contributors
- Statement that any problems or suggestions for the site should be posted as issues, with a link to the Github repo's issues page.

**Comment by jacques-cadet** [comment]
I think we should create an index model to dynamically change the landing page data should we ever need to. Or if you don't think it will ever change we can hardcode it in. Please let me know so I can remove the 
carousel, since it was placed as page filler, initially.

**Comment by sabrown89** [comment]
@jrrickerson I am starting on this issue. I was going to hard code the text into the view unless you have another preference.

We spoke briefly about the project at last week's PyJam (2018-01-04). Thanks 
-Scotty

**Comment by jrrickerson** [comment]
Fixed by #45
